=== daninemcsik/I3I4BP_XMLGyak/XMLTaskI3I4BP/src/XMLSchemaI3I4BP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/XMLSchemaI3I4BP" xmlns:tns="http://www.example.org/XMLSchemaI3I4BP" elementFormDefault="qualified">
	
	<xs:element name="Könyvek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Könyv" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="kiadási_dátum" type="xs:string" />
							<xs:element name="cím" type="xs:string" />
							<xs:element name="kategória" type="xs:string" />
							
							<xs:element name="Szerző">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="szElérhetőség" type="xs:unsignedInt" />
										<xs:element name="szNév" type="xs:string" />
										<xs:element name="szÉletkor" type="xs:unsignedInt" />
									</xs:sequence>
									<xs:attribute name="szkod" type="xs:unsignedInt" use="required" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="Kiadó">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="kiVáros" type="xs:string" />
										<xs:element name="kiCím" type="xs:string" />
										<xs:element name="kiNév" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="kikod" type="xs:unsignedInt" use="required" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="Könyvesbolt">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="kbVáros" type="xs:string" />
										<xs:element name="kbCím" type="xs:string" />
										<xs:element name="kbNév" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="telefonszam" type="xs:unsignedInt" use="required" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="Vásárló">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="vNév" type="xs:string" />
										<xs:element name="vÉletkor" type="xs:unsignedInt" />
										<xs:element name="lakcím">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="vVáros" type="xs:string" />
													<xs:element name="vUtca" type="xs:string" />
													<xs:element name="vHázszám" type="xs:unsignedInt" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="vkod" type="xs:unsignedInt" use="required" />
								</xs:complexType>
							</xs:element>
							
						</xs:sequence>
						<xs:attribute name="kkod" type="xs:unsignedInt" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== daninemcsik/I3I4BP_XMLGyak/XMLTaskI3I4BP/XMLI3I4BP.xml
<?xml version="1.0" encoding="UTF-8"?>
<Könyvek xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://www.example.com/XMLSchemaI3I4BP.xsd">
	
	<Könyv kkod="01">
		<kiadási_dátum>03/15/2019</kiadási_dátum>
		<cím>Senki sem az, akinek látszik</cím>
		<kategória>Irodalom</kategória>
		
		<Szerző szkod="01">
			<szElérhetőség>305256314</szElérhetőség>
			<szNév>Kerry Fisher</szNév>
		</Szerző>
		
		<Kiadó kikod="01">
			<kiVáros>Szeged</kiVáros>
			<kiNév>Szegedi kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="704813192">
			<kbUtcaszám>Szeged, Vitéz utca 30.</kbUtcaszám>
			<kbNév>Szögödi könyvök</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="04">
			<vNév>Kovács Tímea</vNév>
			<vAdatok>25</vAdatok>
			<lakcím>
				<vVáros>Szeged</vVáros>
				<vUtca>Zoltán utca</vUtca>
				<vHázszám>44</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="02">
		<kiadási_dátum>02/10/2018</kiadási_dátum>
		<cím>Nem titok, amit ketten tudnak</cím>
		<kategória>Irodalom</kategória>
		
		<Szerző szkod="02">
			<szElérhetőség>708312943</szElérhetőség>
			<szNév>Robin Cuddy</szNév>
		</Szerző>
		
		<Kiadó kikod="02">
			<kiVáros>Budapest</kiVáros>
			<kiNév>Pesti kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="307318491">
			<kbUtcaszám>Budapest, Szugló utca 40.</kbUtcaszám>
			<kbNév>Book-A-Pest</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="01">
			<vNév>Nagy Ferenc</vNév>
			<vAdatok>42</vAdatok>
			<lakcím>
				<vVáros>Budapest</vVáros>
				<vUtca>Lovarda utca</vUtca>
				<vHázszám>22</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="03">
		<kiadási_dátum>01/11/2020</kiadási_dátum>
		<cím>Tanuljunk rajzolni! - Szafari</cím>
		<kategória>Hobbi</kategória>
		
		<Szerző szkod="03">
			<szElérhetőség>207318219</szElérhetőség>
			<szNév>Ken Follett</szNév>
		</Szerző>
		
		<Kiadó kikod="03">
			<kiVáros>Miskolc</kiVáros>
			<kiNév>Miskolci kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="207431975">
			<kbUtcaszám>Miskolci, Széchenyi utca 20.</kbUtcaszám>
			<kbNév>Libri Miskolc</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="05">
			<vNév>Huszár Zsófia</vNév>
			<vAdatok>33</vAdatok>
			<lakcím>
				<vVáros>Miskolc</vVáros>
				<vUtca>Huba utca</vUtca>
				<vHázszám>55</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="04">
		<kiadási_dátum>05/03/2015</kiadási_dátum>
		<cím>Tanuljunk rajzolni! - Házi kedvencek</cím>
		<kategória>Hobbi</kategória>
		
		<Szerző szkod="04">
			<szElérhetőség>304891398</szElérhetőség>
			<szNév>Fehér Krisztián</szNév>
		</Szerző>
		
		<Kiadó kikod="04">
			<kiVáros>Eger</kiVáros>
			<kiNév>Egri kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="309184751">
			<kbUtcaszám>Eger, Sóház utca 11.</kbUtcaszám>
			<kbNév>Lira Eger</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="03">
			<vNév>Fekete Roland</vNév>
			<vAdatok>20</vAdatok>
			<lakcím>
				<vVáros>Eger</vVáros>
				<vUtca>Gáz utca</vUtca>
				<vHázszám>33</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="05">
		<kiadási_dátum>08/09/2009</kiadási_dátum>
		<cím>World Without End</cím>
		<kategória>Történelem</kategória>
		
		<Szerző szkod="05">
			<szElérhetőség>703189418</szElérhetőség>
			<szNév>Stephen King</szNév>
		</Szerző>
		
		<Kiadó kikod="05">
			<kiVáros>Szombathely</kiVáros>
			<kiNév>Szombathelyi kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="701831951">
			<kbUtcaszám>Szombathely, Forró utca 3.</kbUtcaszám>
			<kbNév>Office Könyvesbolt</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="02">
			<vNév>Kis Tibor</vNév>
			<vAdatok>30</vAdatok>
			<lakcím>
				<vVáros>Szombathely</vVáros>
				<vUtca>Ferencsik utca</vUtca>
				<vHázszám>11</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="06">
		<kiadási_dátum>10/09/2010</kiadási_dátum>
		<cím>The Pillars of The Earth</cím>
		<kategória>Történelem</kategória>
		
		<Szerző szkod="01">
			<szElérhetőség>305256314</szElérhetőség>
			<szNév>Kerry Fisher</szNév>
		</Szerző>
		
		<Kiadó kikod="01">
			<kiVáros>Szeged</kiVáros>
			<kiNév>Szegedi kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="704813192">
			<kbUtcaszám>Szeged, Vitéz utca 30.</kbUtcaszám>
			<kbNév>Szögödi könyvök</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="09">
			<vNév>Lakatos Noel</vNév>
			<vAdatok>50</vAdatok>
			<lakcím>
				<vVáros>Szeged</vVáros>
				<vUtca>Forró utca</vUtca>
				<vHázszám>99</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="07">
		<kiadási_dátum>03/11/2020</kiadási_dátum>
		<cím>Programozz C nyelven</cím>
		<kategória>Számítástechnika</kategória>
		
		<Szerző szkod="02">
			<szElérhetőség>708312943</szElérhetőség>
			<szNév>Robin Cuddy</szNév>
		</Szerző>
		
		<Kiadó kikod="02">
			<kiVáros>Budapest</kiVáros>
			<kiNév>Pesti kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="307318491">
			<kbUtcaszám>Budapest, Szugló utca 40.</kbUtcaszám>
			<kbNév>Book-A-Pest</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="10">
			<vNév>Bognár Éva</vNév>
			<vAdatok>66</vAdatok>
			<lakcím>
				<vVáros>Budapest</vVáros>
				<vUtca>Zöld utca</vUtca>
				<vHázszám>111</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="08">
		<kiadási_dátum>09/11/2020</kiadási_dátum>
		<cím>Számítógépvásárlási túlélőkönyv</cím>
		<kategória>Számítástechnika</kategória>
		
		<Szerző szkod="03">
			<szElérhetőség>207318219</szElérhetőség>
			<szNév>Ken Follett</szNév>
		</Szerző>
		
		<Kiadó kikod="03">
			<kiVáros>Miskolc</kiVáros>
			<kiNév>Miskolci kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="301829231">
			<kbUtcaszám>Miskolc, Iroda utca 4.</kbUtcaszám>
			<kbNév>Office Könyvesbolt</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="08">
			<vNév>Mezei Gábor</vNév>
			<vAdatok>39</vAdatok>
			<lakcím>
				<vVáros>Miskolc</vVáros>
				<vUtca>Gyula utca</vUtca>
				<vHázszám>88</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="09">
		<kiadási_dátum>11/11/2011</kiadási_dátum>
		<cím>The Shining</cím>
		<kategória>Horror</kategória>
		
		<Szerző szkod="04">
			<szElérhetőség>304891398</szElérhetőség>
			<szNév>Fehér Krisztián</szNév>
		</Szerző>
		
		<Kiadó kikod="04">
			<kiVáros>Eger</kiVáros>
			<kiNév>Egri kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="309184751">
			<kbUtcaszám>Eger, Sóház utca 11.</kbUtcaszám>
			<kbNév>Lira Eger</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="06">
			<vNév>Kiss Levente</vNév>
			<vAdatok>18</vAdatok>
			<lakcím>
				<vVáros>Eger</vVáros>
				<vUtca>Fényes utca</vUtca>
				<vHázszám>66</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
	
	
	
	<Könyv kkod="10">
		<kiadási_dátum>10/01/2018</kiadási_dátum>
		<cím>It</cím>
		<kategória>Horror</kategória>
		
		<Szerző szkod="05">
			<szElérhetőség>703189418</szElérhetőség>
			<szNév>Stephen King</szNév>
		</Szerző>
		
		<Kiadó kikod="05">
			<kiVáros>Szombathely</kiVáros>
			<kiNév>Szombathelyi kiadó</kiNév>
		</Kiadó>
		
		<Könyvesbolt telefonszam ="208194851">
			<kbUtcaszám>Szombathely, Vezér utca 6.	</kbUtcaszám>
			<kbNév>Office Könyvesbolt</kbNév>
		</Könyvesbolt>
		
		<Vásárló vkod="07">
			<vNév>Barna Virág</vNév>
			<vAdatok>55</vAdatok>
			<lakcím>
				<vVáros>Szombathely</vVáros>
				<vUtca>Szepes utca</vUtca>
				<vHázszám>77</vHázszám>
			</lakcím>
		</Vásárló>
	</Könyv>
</Könyvek>
