=== daninemcsik/I3I4BP_XMLGyak/I3I4BP_1005/ND_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ND_konyv" xmlns:tns="http://www.example.org/ND_konyv" elementFormDefault="qualified">
		
		
		<xsd:element name="konyvek">
			
        <xsd:complexType>
				<xsd:sequence>
					<xsd:element name="konyv" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="cim" type="xs:string" />
								<xsd:element name="kiadasiEv" type="xs:unsignedShort" />
								<xsd:element name="kiado" type="xs:string" />
								<xsd:element name="szerzo" type="xs:string" maxOccurs="unbounded" />
								<xsd:element name="abstract" type="xs:string" />
							</xsd:sequence>
							<xsd:attribute name="id" type="xs:string" use="required" />
						</xsd:complexType>
					</xsd:element>				
				</xsd:sequence>
			</xsd:complexType>
    </xsd:element>
		
		
</xsd:schema>

=== daninemcsik/I3I4BP_XMLGyak/I3I4BP_1005/ND_konyv.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!-- !DOCTYPE konyvek SYSTEM "ND_konyv.dtd">-->
 
<konyvek xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="http://www.example.com/ND_konyv.xsd">
    <konyv id = "01">

        <cim> Programming Pearls </cim>
        <kiadasiEv> 2006.12.01 </kiadasiEv>
        <kiado> Dorling Kindersley Pvt Ltd </kiado>
        <szerzo> Jon Bentley </szerzo>
        <abstract> The book is about pearl programming. </abstract>


    </konyv>

    <konyv id = "02">

        <cim>  Introduction to Algorithms </cim>
        <kiadasiEv> 1990 </kiadasiEv>
        <kiado> MIT P-ress </kiado>
        <szerzo> Thomas H. Cormen </szerzo>
        <szerzo> Charles E. Leiserson</szerzo>
        <szerzo> Ronald L. Rivest </szerzo>
        <szerzo> Clifford Stein </szerzo>
		<abstract> The book is about basic algorithms.</abstract>
    </konyv>

    <konyv id = "03">

        <cim> HTML and CSS: Design and Build Websites </cim>
        <kiadasiEv>  2011. okt√≥ber 25. </kiadasiEv>
        <kiado> Wiley </kiado>
        <szerzo> Jon Duckett </szerzo>
        <abstract> The book is about web design.</abstract>


    </konyv>
 
</konyvek>
