=== daninemcsik/I3I4BP_XMLGyak/I3I4BP_0928/ND_konyv.dtd
<!ELEMENT konyvek (konyv)+ >
<!ELEMENT konyv (cim, kiadasiEv, kiado, (szerzo)+) >
<!ELEMENT cim (#PCDATA) >
<!ELEMENT kiadasiEv (#PCDATA) >
<!ELEMENT kiado (#PCDATA) >
<!ELEMENT szerzo (#PCDATA) >

<!ATTLIST konyv id CDATA #REQUIRED >
<!ATTLIST konyv abstract (true | false) #REQUIRED >

=== daninemcsik/I3I4BP_XMLGyak/I3I4BP_0928/ND_konyv.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!DOCTYPE konyvek SYSTEM "ND_konyv.dtd">

<konyvek>
    <konyv id = "01" abstract = "true">

        <cim> Programming Pearls </cim>
        <kiadasiEv> 2006.12.01 </kiadasiEv>
        <kiado> Dorling Kindersley Pvt Ltd </kiado>
        <szerzo> Jon Bentley </szerzo>


    </konyv>

    <konyv id = "02" abstract = "true">

        <cim>  Introduction to Algorithms </cim>
        <kiadasiEv> 1990 </kiadasiEv>
        <kiado> MIT P-ress </kiado>
        <szerzo> Thomas H. Cormen </szerzo>
        <szerzo> Charles E. Leiserson</szerzo>
        <szerzo> Ronald L. Rivest </szerzo>
        <szerzo> Clifford Stein </szerzo>

    </konyv>

    <konyv id = "03" abstract = "true">

        <cim> HTML and CSS: Design and Build Websites </cim>
        <kiadasiEv>  2011. okt√≥ber 25. </kiadasiEv>
        <kiado> Wiley </kiado>
        <szerzo> Jon Duckett </szerzo>


    </konyv>
</konyvek>
